on:
  pull_request:
    paths-ignore: &ignore-paths
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    branches: [ 'master' ]
    paths-ignore: *ignore-paths

name: Mutation test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.5' ]

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Run infection
        run: |
          make build v="${PHP_VERSION}"
          make mutation-test v="${PHP_VERSION}"
        env:
          PHP_VERSION: ${{ matrix.php }}
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
