name: Mutation test

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'tests/**'
      - 'phpunit.xml.dist'
      - 'infection.json.dist'
      - 'composer.json'
      - '.github/workflows/mutation.yml'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.5' ]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run infection
        run: |
          make build v="${PHP_VERSION}"
          make mutation-test v="${PHP_VERSION}"
        env:
          PHP_VERSION: ${{ matrix.php }}
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
